// Date: 30.10.2014 08:45:52
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package assets.bulbs.models.ModelOfficeLight2X32;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelOfficeLight2X32 extends ModelBase
{
  //fields
    ModelRenderer Side1;
    ModelRenderer Side2;
    ModelRenderer Side3;
    ModelRenderer Side4;
    ModelRenderer Light;
    ModelRenderer Pole;
    ModelRenderer Top;
  
  public ModelOfficeLight2X32()
  {
    textureWidth = 128;
    textureHeight = 128;

      Side1 = new ModelRenderer(this, 0, 7);
      Side1.addBox(-16F, -32F, 14F, 32, 5, 2);
      Side1.setRotationPoint(0F, 24F, 0F);
      Side1.setTextureSize(128, 128);
      Side1.mirror = true;
      setRotation(Side1, 0F, 3.141593F, 0F);
      Side2 = new ModelRenderer(this, 0, 0);
      Side2.addBox(-14F, -32F, -16F, 28, 5, 2);
      Side2.setRotationPoint(0F, 24F, 0F);
      Side2.setTextureSize(128, 128);
      Side2.mirror = true;
      setRotation(Side2, 0F, 1.570796F, 0F);
      Side3 = new ModelRenderer(this, 0, 7);
      Side3.addBox(-16F, -32F, 14F, 32, 5, 2);
      Side3.setRotationPoint(0F, 24F, 0F);
      Side3.setTextureSize(128, 128);
      Side3.mirror = true;
      setRotation(Side3, 0F, 0F, 0F);
      Side4 = new ModelRenderer(this, 0, 0);
      Side4.addBox(-14F, -32F, -16F, 28, 5, 2);
      Side4.setRotationPoint(0F, 24F, 0F);
      Side4.setTextureSize(128, 128);
      Side4.mirror = true;
      setRotation(Side4, 0F, -1.570796F, 0F);
      Light = new ModelRenderer(this, 0, 14);
      Light.addBox(-12F, -31F, -12F, 24, 4, 24);
      Light.setRotationPoint(0F, 24F, 0F);
      Light.setTextureSize(128, 128);
      Light.mirror = true;
      setRotation(Light, 0F, 0F, 0F);
      Pole = new ModelRenderer(this, 82, 0);
      Pole.addBox(-4F, -26F, -4F, 8, 26, 8);
      Pole.setRotationPoint(0F, 24F, 0F);
      Pole.setTextureSize(128, 128);
      Pole.mirror = true;
      setRotation(Pole, 0F, 0F, 0F);
      Top = new ModelRenderer(this, 0, 43);
      Top.addBox(-15F, -27F, -15F, 30, 1, 30);
      Top.setRotationPoint(0F, 24F, 0F);
      Top.setTextureSize(128, 128);
      Top.mirror = true;
      setRotation(Top, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    Side1.render(f5);
    Side2.render(f5);
    Side3.render(f5);
    Side4.render(f5);
    Light.render(f5);
    Pole.render(f5);
    Top.render(f5);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }

    public void renderModel(float f5) {
        Side1.render(f5);
        Side2.render(f5);
        Side3.render(f5);
        Side4.render(f5);
        Light.render(f5);
        Pole.render(f5);


    }

    public void renderAlpha(float f5) {
        Side1.render(f5);
        Side2.render(f5);
        Side3.render(f5);
        Side4.render(f5);
        Light.render(f5);
        Top.render(f5);
    }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
  }

}
