// Date: 22.10.2014 11:00:36
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package assets.bulbs.models;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelGridLightCon2FarX32 extends ModelBase
{
  //fields
    ModelRenderer Bottom;
    ModelRenderer Light;
    ModelRenderer Alpha;
    ModelRenderer Cage;

  public ModelGridLightCon2FarX32()
  {
    textureWidth = 256;
    textureHeight = 192;
    
      Bottom = new ModelRenderer(this, 0, 0);
      Bottom.addBox(-16F, 0F, -12F, 32, 2, 24);
      Bottom.setRotationPoint(0F, 22F, 0F);
      Bottom.setTextureSize(256, 128);
      Bottom.mirror = true;
      setRotation(Bottom, 0F, 0F, 0F);
      Light = new ModelRenderer(this, 0, 98);
      Light.addBox(-16F, 0F, -8F, 32, 2, 16);
      Light.setRotationPoint(0F, 20F, 0F);
      Light.setTextureSize(256, 128);
      Light.mirror = true;
      setRotation(Light, 0F, 0F, 0F);
      Alpha = new ModelRenderer(this, 113, 29);
      Alpha.addBox(-16F, 0F, -9F, 32, 3, 18);
      Alpha.setRotationPoint(0F, 19F, 0F);
      Alpha.setTextureSize(256, 128);
      Alpha.mirror = true;
      setRotation(Alpha, 0F, 0F, 0F);
      Cage = new ModelRenderer(this, 113, 0);
      Cage.addBox(-16F, 0F, -10F, 32, 4, 20);
      Cage.setRotationPoint(0F, 18F, 0F);
      Cage.setTextureSize(256, 128);
      Cage.mirror = true;
      setRotation(Cage, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    Bottom.render(f5);
    Light.render(f5);
    Alpha.render(f5);
    Cage.render(f5);
  }

    public void renderModel(float f5) {
        Bottom.render(f5);
        Light.render(f5);
        Cage.render(f5);
    }

    public void renderAlpha(float f5) {
        Alpha.render(f5);
    }

    private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, entity
    );
  }

}
