// Date: 21.10.2014 08:52:58
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package assets.bulbs.models;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelThinLightCon3X32 extends ModelBase
{
  //fields
    ModelRenderer Bottom;
    ModelRenderer Bottom2;
    ModelRenderer Light;
    ModelRenderer Light2;
    ModelRenderer Alpha2;
    ModelRenderer Alpha;
  
  public ModelThinLightCon3X32()
  {
    textureWidth = 128;
    textureHeight = 64;
    
      Bottom = new ModelRenderer(this, 0, 0);
      Bottom.addBox(-16F, -1F, -4F, 32, 1, 8);
      Bottom.setRotationPoint(0F, 24F, 0F);
      Bottom.setTextureSize(128, 64);
      Bottom.mirror = true;
      setRotation(Bottom, 0F, 0F, 0F);
      Bottom2 = new ModelRenderer(this, 72, 0);
      Bottom2.addBox(-4F, -1F, 4F, 8, 1, 12);
      Bottom2.setRotationPoint(0F, 24F, 0F);
      Bottom2.setTextureSize(128, 64);
      Bottom2.mirror = true;
      setRotation(Bottom2, 0F, 0F, 0F);
      Light = new ModelRenderer(this, 0, 59);
      Light.addBox(-16F, -1.5F, -2F, 32, 1, 4);
      Light.setRotationPoint(0F, 24F, 0F);
      Light.setTextureSize(128, 64);
      Light.mirror = true;
      setRotation(Light, 0F, 0F, 0F);
      Light2 = new ModelRenderer(this, 72, 13);
      Light2.addBox(-2F, -1.5F, 2F, 4, 1, 14);
      Light2.setRotationPoint(0F, 24F, 0F);
      Light2.setTextureSize(128, 64);
      Light2.mirror = true;
      setRotation(Light2, 0F, 0F, 0F);
      Alpha2 = new ModelRenderer(this, 72, 28);
      Alpha2.addBox(-3F, -2F, 3F, 6, 1, 13);
      Alpha2.setRotationPoint(0F, 24F, 0F);
      Alpha2.setTextureSize(128, 64);
      Alpha2.mirror = true;
      setRotation(Alpha2, 0F, 0F, 0F);
      Alpha = new ModelRenderer(this, 0, 52);
      Alpha.addBox(-3F, -2F, -3F, 32, 1, 6);
      Alpha.setRotationPoint(-13F, 24F, 0F);
      Alpha.setTextureSize(128, 64);
      Alpha.mirror = true;
      setRotation(Alpha, 0F, 0F, 0F);
  }
  
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
    super.render(entity, f, f1, f2, f3, f4, f5);
    setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    Bottom.render(f5);
    Bottom2.render(f5);
    Light.render(f5);
    Light2.render(f5);
    Alpha2.render(f5);
    Alpha.render(f5);
  }

    public void renderModel(float f5) {
        Bottom.render(f5);
        Bottom2.render(f5);
        Light.render(f5);
        Light2.render(f5);
    }

    public void renderAlpha(float f5) {
        Alpha2.render(f5);
        Alpha.render(f5);
    }

  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity)
  {
    super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
  }

}
