// Date: 24.10.2014 23:19:09
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package assets.bulbs.models.ModelPoleLightX32;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelPoleLightX32 extends ModelBase
{
    //fields
    ModelRenderer Alpha;
    ModelRenderer Light;

    public ModelPoleLightX32(int lightHeight, float lightYpos, int alphaTextureOffset) {

        textureWidth = 64;
        textureHeight = 96;

        Alpha = new ModelRenderer(this, alphaTextureOffset, 0);
        Alpha.addBox(-4F, -32F, -4F, 8, 32, 8);
        Alpha.setRotationPoint(0F, 24F, 0F);
        Alpha.setTextureSize(64, 96);
        Alpha.mirror = true;
        setRotation(Alpha, 0F, 0F, 0F);
        Light = new ModelRenderer(this, 0, 42);
        Light.addBox(-2F, lightYpos, -2F, 4, lightHeight, 4);
        Light.setRotationPoint(0F, 24F, 0F);
        Light.setTextureSize(64, 96);
        Light.mirror = true;
        setRotation(Light, 0F, 0F, 0F);
    }

    public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5) {
        super.render(entity, f, f1, f2, f3, f4, f5);
        setRotationAngles(f, f1, f2, f3, f4, f5, entity);
        Alpha.render(f5);
        Light.render(f5);
    }


    public void renderModel(float f5) {
        Light.render(f5);
    }

    public void renderAlpha(float f5) {
        Alpha.render(f5);
    }


    private void setRotation(ModelRenderer model, float x, float y, float z)
    {
        model.rotateAngleX = x;
        model.rotateAngleY = y;
        model.rotateAngleZ = z;
    }

    public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity)
    {
        super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
    }

}
